#!/bin/sh -e
exec 2>&1

#!/bin/bash
if [ -z "$CLUSTER_NAME" ]; then
        echo >&2 'Error:  You need to specify CLUSTER_NAME'
        exit 1
fi

if [ -z "$DISCOVERY_SERVICE" ]; then
        echo >&2 'Error:  You need to specify DISCOVERY_SERVICE'
        exit 1
fi


sed -e "s;%ADMIN_USER%;${ADMIN_USER:-admin};g" \
-e "s;%ADMIN_PASS%;${ADMIN_PASS:-admin};g" \
-e "s;%ADMIN_PORT%;${ADMIN_PORT:-6032};g" \
/etc/proxysql.tmpl > /etc/proxysql.cnf

exec /usr/bin/proxysql -f -c /etc/proxysql.cnf 
